// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bzajmrwdrnykrubwrsly.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ6YWptcndkcm55a3J1Yndyc2x5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1MzI2MjEsImV4cCI6MjA2NzEwODYyMX0.Z1g0IlX4KPxV-hXbSSZUHio8lTsTwDd7iON4xTSNQbg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});